insert into PLAYER (
    PLAYER_ID, FULL_NAME, POSITIONS, OVERALL, 
    INSIDE_SCORING, MID_RANGE_SCORING, THREE_POINT_SCORING, 
    INTERIOR_DEFENSE, PERIMETER_DEFENSE, PLAYMAKING, 
    REBOUNDING, PHYSICALS, IQ
) VALUES 
	(1, 'Michael Jordan', 'SG', 99, 'A+', 'A+', 'A-', 'B+', 'A+', 'A+', 'B-', 'A+', 'A+'),
	(2, 'Lebron James', 'SF', 99, 'A+', 'A', 'A-', 'A-', 'A+', 'A+', 'B', 'A+', 'A+'),
	(3, 'Larry Bird', 'SF/PF', 98, 'A+', 'A+', 'A+', 'A', 'A', 'A', 'B+', 'D', 'A+'),
	(4, 'Wilt Chamberlain', 'C', 98, 'A+', 'C-', 'F', 'A+', 'C', 'A-', 'A+', 'A+', 'A+'),
	(5, 'Kobe Bryant', 'SG/SF', 98, 'A+', 'A+', 'A', 'C+', 'A+', 'A+', 'C+', 'A+', 'A+'),
	(6, 'Magic Johnson', 'PG/PF', 98, 'A+', 'A', 'B+', 'B', 'B', 'A+', 'A', 'A+', 'A+'),
	(7, 'Shaquille Oneal', 'C', 98, 'A+', 'F', 'F', 'A+', 'C', 'B-', 'A+', 'A+', 'A'),
	(8, 'Kareem Abdul-Jabbar', 'C', 98, 'A+', 'B+', 'D-', 'A+', 'C', 'C', 'A+', 'A+', 'A+'),
	(9, 'Hakeem Olajuwon', 'C/PF', 98, 'A+', 'A', 'C', 'A+', 'C-', 'C+', 'A+', 'B-', 'A+'),
	(10, 'Tim Duncan', 'PF/C', 98, 'A+', 'A+', 'C+', 'A+', 'B-', 'C+', 'A+', 'A-', 'A+'),
	(11, 'Bill Russell', 'C/PF', 98, 'A+', 'F', 'F', 'A+', 'B', 'B-', 'A+', 'A+', 'A+'),
	(12, 'Julius Erving', 'SF/SG', 97, 'A+', 'A', 'B+', 'A-', 'A+', 'A', 'B+', 'A+', 'A+'),
	(13, 'Giannis Antetokounmpo', 'PF', 97, 'A+', 'A-', 'C+', 'A+', 'A+', 'A', 'B+', 'A+', 'A'),
	(14, 'Kevin Durant', 'SF', 97, 'A+', 'A+', 'A', 'B', 'B+', 'A-', 'B-', 'A-', 'A+'),
	(15, 'Nikola Jokic', 'C', 97, 'A+', 'A', 'A-', 'B+', 'C+', 'A+', 'A', 'B', 'A+'),
	(16, 'Stephen Curry', 'PG', 97, 'A+', 'A+', 'A+', 'F', 'B+', 'A+', 'D+', 'A-', 'A+'),
	(17, 'Oscar Robertson', 'PG/SG', 97, 'A+', 'A', 'B', 'C', 'A', 'A+', 'A', 'A+', 'A+'),
	(18, 'Dirk Nowitzki', 'PF/C', 97, 'A+', 'A+', 'A', 'B', 'D-', 'B', 'A-', 'C', 'B'),
	(19, 'Kevin Garnett', 'PF/C', 97, 'A+', 'A', 'C+', 'A+', 'C-', 'B+', 'A+', 'A+', 'A+'),
	(20, 'Allen Iverson', 'PG', 96, 'A+', 'A', 'A-', 'F', 'B+', 'A', 'D-', 'A+', 'A+'),
	(21, 'Derrick Rose', 'PG', 96, 'A+', 'A', 'B', 'C-', 'A-', 'A', 'C+', 'A+', 'A+'),
	(22, 'James Harden', 'SG', 96, 'A+', 'A-', 'A', 'C+', 'B', 'A+', 'C+', 'A+', 'A+'),
	(23, 'Steve Nash', 'PG', 96, 'A+', 'A', 'A+', 'F', 'B', 'A+', 'B-', 'B+', 'A+'),
	(24, 'Russell Westbrook', 'PG', 96, 'A+', 'A-', 'B', 'D+', 'A', 'A+', 'A', 'A+', 'A-'),
	(25, 'Karl Malone', 'PF', 96, 'A+', 'A+', 'B', 'A-', 'C-', 'B+', 'A+', 'A+', 'A'),
	(26, 'Charles Barkley*', 'PF', 96, 'A', 'A-', 'B', 'B', 'C+', 'B+', 'A+', 'A+', 'A-'),
	(27, 'Joel Embiid', 'C', 96, 'A', 'A-', 'B+', 'A+', 'C+', 'C', 'A', 'B+', 'A'),
	(28, 'David Robinson', 'C', 96, 'A+', 'A', 'C', 'A+', 'C', 'D', 'A', 'A', 'A'),
	(29, 'Moses Malone', 'C', 96, 'A+', 'B', 'F', 'A+', 'C', 'D', 'A+', 'A+', 'A+'),
	(30, 'Bob Cousy', 'PG', 95, 'A', 'A+', 'A-', 'F', 'A-', 'A+', 'B+', 'A', 'A+'),
	(31, 'Bill Walton', 'C', 95, 'A+', 'A-', 'D-', 'A', 'C-', 'B+', 'A+', 'B', 'A+'),
	(32, 'Bob Pettit', 'PF', 95, 'A+', 'A+', 'B+', 'A', 'D+', 'C+', 'A+', 'B+', 'A-'),
	(33, 'Wes Unseld', 'C/PF', 94, 'A+', 'B+', 'B-', 'A-', 'B', 'A-', 'A+', 'A+', 'A'),
	(34, 'Bob McAdoo', 'C/PF', 94, 'A+', 'A', 'F', 'A+', 'B-', 'B', 'A+', 'A+', 'A'),
	(35, 'Dave Cowens', 'C/PF', 94, 'A+', 'A', 'B-', 'A-', 'C+', 'C-', 'A+', 'B+', 'A+'),
	(36, 'Willis Reed', 'C/PF', 94, 'A+', 'A', 'F', 'A-', 'C', 'D+', 'A+', 'A+', 'A-')
;
